name: CI
on:
  push: { branches: [main] }
  pull_request:
jobs:
  build-test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: brew install xcodegen && xcodegen generate
      - name: Test
        run: >
          xcodebuild test -skipMacroValidation -skipPackagePluginValidation -project CortanaCore.xcodeproj -scheme CortanaCore
          -destination 'platform=iOS Simulator,name=iPhone 15' CODE_SIGNING_ALLOWED=NO
